[2025-07-09T20:37:57.713+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T20:37:57.810+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-09T20:35:30.246629+00:00 [queued]>
[2025-07-09T20:37:57.831+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-09T20:35:30.246629+00:00 [queued]>
[2025-07-09T20:37:57.832+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-09T20:37:57.857+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_drift_monitoring> on 2025-07-09 20:35:30.246629+00:00
[2025-07-09T20:37:57.899+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_monitoring_dag', 'run_drift_monitoring', 'manual__2025-07-09T20:35:30.246629+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/daily_monitoring_dag.py', '--cfg-path', '/tmp/tmpbvumsv9j']
[2025-07-09T20:37:57.902+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask run_drift_monitoring
[2025-07-09T20:37:57.906+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=164) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T20:37:57.908+0000] {standard_task_runner.py:63} INFO - Started process 182 to run task
[2025-07-09T20:37:57.936+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-09T20:37:58.018+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-09T20:35:30.246629+00:00 [running]> on host 87ab12aa1dea
[2025-07-09T20:37:58.185+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_monitoring_dag' AIRFLOW_CTX_TASK_ID='run_drift_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T20:35:30.246629+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T20:35:30.246629+00:00'
[2025-07-09T20:37:58.188+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T20:37:58.227+0000] {logging_mixin.py:188} INFO - [INFO] Monitoring drift: ref=2025-07-04-15, current=2025-07-05-15
[2025-07-09T20:37:58.227+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T20:37:58.228+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_monitoring_dag.py", line 65, in run_monitoring_wrapper
    run_monitoring(reference_ts=ref_ts, current_ts=cur_ts)
  File "/opt/airflow/github_pipeline/monitor.py", line 49, in run_monitoring
    raise FileNotFoundError(f"[ERROR] Reference file not found: {ref_file}")
FileNotFoundError: [ERROR] Reference file not found: features/actor_features_2025-07-04-15.parquet
[2025-07-09T20:37:58.242+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_monitoring_dag, task_id=run_drift_monitoring, run_id=manual__2025-07-09T20:35:30.246629+00:00, execution_date=20250709T203530, start_date=20250709T203757, end_date=20250709T203758
[2025-07-09T20:37:58.258+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 69 for task run_drift_monitoring ([ERROR] Reference file not found: features/actor_features_2025-07-04-15.parquet; 182)
[2025-07-09T20:37:58.298+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-09T20:37:58.355+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T20:37:58.361+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
