[2025-07-04T11:42:23.228+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T11:42:23.292+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.run_inference manual__2025-07-04T11:37:18.988421+00:00 [queued]>
[2025-07-04T11:42:23.303+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.run_inference manual__2025-07-04T11:37:18.988421+00:00 [queued]>
[2025-07-04T11:42:23.303+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-04T11:42:23.317+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_inference> on 2025-07-04 11:37:18.988421+00:00
[2025-07-04T11:42:23.332+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=238) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-04T11:42:23.335+0000] {standard_task_runner.py:63} INFO - Started process 240 to run task
[2025-07-04T11:42:23.330+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'run_inference', 'manual__2025-07-04T11:37:18.988421+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/inference_dag.py', '--cfg-path', '/tmp/tmpks3tz5wf']
[2025-07-04T11:42:23.336+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_inference
[2025-07-04T11:42:23.352+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T11:42:23.395+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.run_inference manual__2025-07-04T11:37:18.988421+00:00 [running]> on host 575da08c5502
[2025-07-04T11:42:23.527+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='run_inference' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T11:37:18.988421+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T11:37:18.988421+00:00'
[2025-07-04T11:42:23.528+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T11:42:24.102+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T11:42:24.109+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/github_pipeline/inference.py", line 5, in run_inference
    import joblib
ModuleNotFoundError: No module named 'joblib'
[2025-07-04T11:42:24.130+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_github_inference, task_id=run_inference, run_id=manual__2025-07-04T11:37:18.988421+00:00, execution_date=20250704T113718, start_date=20250704T114223, end_date=20250704T114224
[2025-07-04T11:42:24.145+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task run_inference (No module named 'joblib'; 240)
[2025-07-04T11:42:24.197+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T11:42:24.216+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T11:42:24.217+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
