[2025-07-04T14:45:53.356+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T14:45:53.432+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T14:45:44.657542+00:00 [queued]>
[2025-07-04T14:45:53.446+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T14:45:44.657542+00:00 [queued]>
[2025-07-04T14:45:53.447+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-04T14:45:53.465+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-07-04 14:45:44.657542+00:00
[2025-07-04T14:45:53.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=283) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-04T14:45:53.500+0000] {standard_task_runner.py:63} INFO - Started process 296 to run task
[2025-07-04T14:45:53.495+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weekly_model_retraining', 'retrain_model', 'manual__2025-07-04T14:45:44.657542+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/retraining_dag.py', '--cfg-path', '/tmp/tmppwag89wi']
[2025-07-04T14:45:53.504+0000] {standard_task_runner.py:91} INFO - Job 7: Subtask retrain_model
[2025-07-04T14:45:53.533+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T14:45:53.595+0000] {task_command.py:426} INFO - Running <TaskInstance: weekly_model_retraining.retrain_model manual__2025-07-04T14:45:44.657542+00:00 [running]> on host e8e8a486d025
[2025-07-04T14:45:53.742+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='weekly_model_retraining' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T14:45:44.657542+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T14:45:44.657542+00:00'
[2025-07-04T14:45:53.745+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T14:45:53.760+0000] {logging_mixin.py:188} INFO - [INFO] Found latest timestamp: 2024-01-01-16
[2025-07-04T14:45:53.760+0000] {logging_mixin.py:188} INFO - [INFO] Starting model training...
[2025-07-04T14:45:54.052+0000] {logging_mixin.py:188} WARNING - 2025/07/04 14:45:54 INFO mlflow.tracking.fluent: Experiment with name 'anomaly_detection_github' does not exist. Creating a new experiment.
[2025-07-04T14:45:54.169+0000] {logging_mixin.py:188} WARNING - 2025/07/04 14:45:54 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-07-04T14:45:55.381+0000] {logging_mixin.py:188} INFO -        actor  anomaly_score  anomaly
0    00000o1       0.208115    False
1     00b7ce       0.246393    False
2  01-Deepak       0.246393    False
3      0130w       0.221535    False
4    01anuja       0.236908    False
[2025-07-04T14:45:55.386+0000] {logging_mixin.py:188} INFO - [INFO] Training completed successfully.
[2025-07-04T14:45:55.387+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-07-04T14:45:55.389+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T14:45:55.403+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weekly_model_retraining, task_id=retrain_model, run_id=manual__2025-07-04T14:45:44.657542+00:00, execution_date=20250704T144544, start_date=20250704T144553, end_date=20250704T144555
[2025-07-04T14:45:55.466+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-07-04T14:45:55.485+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T14:45:55.489+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
