[2025-07-06T00:25:33.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T00:25:33.776+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:25:32.115452+00:00 [queued]>
[2025-07-06T00:25:33.781+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:25:32.115452+00:00 [queued]>
[2025-07-06T00:25:33.782+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-06T00:25:33.790+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_parse_github_data> on 2025-07-06 00:25:32.115452+00:00
[2025-07-06T00:25:33.798+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T00:25:33.798+0000] {standard_task_runner.py:63} INFO - Started process 493 to run task
[2025-07-06T00:25:33.798+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'download_and_parse_github_data', 'manual__2025-07-06T00:25:32.115452+00:00', '--job-id', '10', '--raw', '--subdir', 'DAGS_FOLDER/daily_github_inference.py', '--cfg-path', '/tmp/tmp465fs0_1']
[2025-07-06T00:25:33.800+0000] {standard_task_runner.py:91} INFO - Job 10: Subtask download_and_parse_github_data
[2025-07-06T00:25:33.810+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T00:25:33.836+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:25:32.115452+00:00 [running]> on host 99d948e6500d
[2025-07-06T00:25:34.067+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='download_and_parse_github_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T00:25:32.115452+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T00:25:32.115452+00:00'
[2025-07-06T00:25:34.067+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T00:25:34.076+0000] {logging_mixin.py:188} INFO - [INFO] Starting ingestion for timestamp: 2025-07-05-15
[2025-07-06T00:25:34.375+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T00:25:34.376+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_github_inference.py", line 21, in run_ingestion_wrapper
    run_ingestion(timestamp=ts)
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 71, in run_ingestion
    raw_path = download_gharchive_json_gz(timestamp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 33, in download_gharchive_json_gz
    urlretrieve(url, out_path)
  File "/usr/local/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
[2025-07-06T00:25:34.383+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_github_inference, task_id=download_and_parse_github_data, run_id=manual__2025-07-06T00:25:32.115452+00:00, execution_date=20250706T002532, start_date=20250706T002533, end_date=20250706T002534
[2025-07-06T00:25:34.392+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 10 for task download_and_parse_github_data (HTTP Error 403: Forbidden; 493)
[2025-07-06T00:25:34.414+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T00:25:34.431+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T00:25:34.432+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
