[2025-07-09T18:12:29.085+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T18:12:29.117+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-06T00:00:00+00:00 [queued]>
[2025-07-09T18:12:29.127+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-06T00:00:00+00:00 [queued]>
[2025-07-09T18:12:29.129+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-09T18:12:29.142+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_parse_github_data> on 2025-07-06 00:00:00+00:00
[2025-07-09T18:12:29.158+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=431) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T18:12:29.161+0000] {standard_task_runner.py:63} INFO - Started process 439 to run task
[2025-07-09T18:12:29.159+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'download_and_parse_github_data', 'scheduled__2025-07-06T00:00:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/daily_github_inference.py', '--cfg-path', '/tmp/tmpnof7jvel']
[2025-07-09T18:12:29.163+0000] {standard_task_runner.py:91} INFO - Job 33: Subtask download_and_parse_github_data
[2025-07-09T18:12:29.187+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-09T18:12:29.231+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-06T00:00:00+00:00 [running]> on host dbf9e19c1827
[2025-07-09T18:12:29.327+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='download_and_parse_github_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-06T00:00:00+00:00'
[2025-07-09T18:12:29.328+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T18:12:29.342+0000] {logging_mixin.py:188} INFO - [INFO] Starting ingestion for timestamp: 2025-07-05-15
[2025-07-09T18:12:29.343+0000] {logging_mixin.py:188} INFO - [INFO] Raw file already exists: data/raw/2025-07-05-15.json.gz
[2025-07-09T18:12:37.905+0000] {credentials.py:567} INFO - Found credentials in environment variables.
[2025-07-09T18:12:39.269+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T18:12:39.272+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_github_inference.py", line 35, in run_ingestion_wrapper
    run_ingestion(timestamp=ts)
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 85, in run_ingestion
    out_path = f"s3://{bucket_name}/{relative_path}" if is_s3_enabled() else f"data/{relative_path}"
                       ^^^^^^^^^^^
NameError: name 'bucket_name' is not defined
[2025-07-09T18:12:39.330+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_github_inference, task_id=download_and_parse_github_data, run_id=scheduled__2025-07-06T00:00:00+00:00, execution_date=20250706T000000, start_date=20250709T181229, end_date=20250709T181239
[2025-07-09T18:12:39.376+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 33 for task download_and_parse_github_data (name 'bucket_name' is not defined; 439)
[2025-07-09T18:12:39.448+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-09T18:12:39.487+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T18:12:39.494+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
