[2025-07-09T18:07:04.272+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T18:07:04.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-08T00:00:00+00:00 [queued]>
[2025-07-09T18:07:04.533+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-08T00:00:00+00:00 [queued]>
[2025-07-09T18:07:04.536+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-09T18:07:04.610+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_parse_github_data> on 2025-07-08 00:00:00+00:00
[2025-07-09T18:07:04.647+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=165) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T18:07:04.650+0000] {standard_task_runner.py:63} INFO - Started process 184 to run task
[2025-07-09T18:07:04.656+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'download_and_parse_github_data', 'scheduled__2025-07-08T00:00:00+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/daily_github_inference.py', '--cfg-path', '/tmp/tmplnjh_gex']
[2025-07-09T18:07:04.667+0000] {standard_task_runner.py:91} INFO - Job 28: Subtask download_and_parse_github_data
[2025-07-09T18:07:04.713+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-09T18:07:04.843+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.download_and_parse_github_data scheduled__2025-07-08T00:00:00+00:00 [running]> on host dbf9e19c1827
[2025-07-09T18:07:05.401+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='download_and_parse_github_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-08T00:00:00+00:00'
[2025-07-09T18:07:05.412+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T18:07:05.663+0000] {logging_mixin.py:188} INFO - [INFO] Starting ingestion for timestamp: 2025-07-07-15
[2025-07-09T18:07:10.314+0000] {logging_mixin.py:188} INFO - [INFO] Downloaded https://data.gharchive.org/2025-07-07-15.json.gz to data/raw/2025-07-07-15.json.gz
[2025-07-09T18:07:29.173+0000] {credentials.py:567} INFO - Found credentials in environment variables.
[2025-07-09T18:07:30.405+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T18:07:30.406+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_github_inference.py", line 35, in run_ingestion_wrapper
    run_ingestion(timestamp=ts)
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 85, in run_ingestion
    out_path = f"s3://{bucket_name}/{relative_path}" if is_s3_enabled() else f"data/{relative_path}"
                       ^^^^^^^^^^^
NameError: name 'bucket_name' is not defined
[2025-07-09T18:07:30.434+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_github_inference, task_id=download_and_parse_github_data, run_id=scheduled__2025-07-08T00:00:00+00:00, execution_date=20250708T000000, start_date=20250709T180704, end_date=20250709T180730
[2025-07-09T18:07:30.461+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 28 for task download_and_parse_github_data (name 'bucket_name' is not defined; 184)
[2025-07-09T18:07:30.517+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-09T18:07:30.540+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T18:07:30.541+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
