[2025-07-06T00:42:18.663+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-06T00:42:18.688+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:42:16.975421+00:00 [queued]>
[2025-07-06T00:42:18.693+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:42:16.975421+00:00 [queued]>
[2025-07-06T00:42:18.694+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-06T00:42:18.706+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_parse_github_data> on 2025-07-06 00:42:16.975421+00:00
[2025-07-06T00:42:18.714+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=198) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-06T00:42:18.714+0000] {standard_task_runner.py:63} INFO - Started process 200 to run task
[2025-07-06T00:42:18.714+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'download_and_parse_github_data', 'manual__2025-07-06T00:42:16.975421+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/daily_github_inference.py', '--cfg-path', '/tmp/tmpwii4jvc1']
[2025-07-06T00:42:18.716+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask download_and_parse_github_data
[2025-07-06T00:42:18.727+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-06T00:42:18.747+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-06T00:42:16.975421+00:00 [running]> on host ab064270a724
[2025-07-06T00:42:18.988+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='download_and_parse_github_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-06T00:42:16.975421+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-06T00:42:16.975421+00:00'
[2025-07-06T00:42:18.988+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-06T00:42:19.023+0000] {logging_mixin.py:188} INFO - [INFO] Starting ingestion for timestamp: 2025-07-05-15
[2025-07-06T00:42:19.023+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-06T00:42:19.023+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_github_inference.py", line 21, in run_ingestion_wrapper
    run_ingestion(timestamp=ts)
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 79, in run_ingestion
    raw_path = download_gharchive_json_gz(timestamp)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 36, in download_gharchive_json_gz
    response = requests.get(url, headers=headers, stream=True)
               ^^^^^^^^
NameError: name 'requests' is not defined
[2025-07-06T00:42:19.034+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_github_inference, task_id=download_and_parse_github_data, run_id=manual__2025-07-06T00:42:16.975421+00:00, execution_date=20250706T004216, start_date=20250706T004218, end_date=20250706T004219
[2025-07-06T00:42:19.043+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task download_and_parse_github_data (name 'requests' is not defined; 200)
[2025-07-06T00:42:19.054+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-06T00:42:19.070+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-06T00:42:19.071+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
