[2025-07-09T18:14:55.135+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-09T18:14:55.161+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-09T18:09:43.991049+00:00 [queued]>
[2025-07-09T18:14:55.167+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-09T18:09:43.991049+00:00 [queued]>
[2025-07-09T18:14:55.167+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-07-09T18:14:55.177+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): download_and_parse_github_data> on 2025-07-09 18:09:43.991049+00:00
[2025-07-09T18:14:55.186+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=564) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-09T18:14:55.187+0000] {standard_task_runner.py:63} INFO - Started process 567 to run task
[2025-07-09T18:14:55.186+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_github_inference', 'download_and_parse_github_data', 'manual__2025-07-09T18:09:43.991049+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/daily_github_inference.py', '--cfg-path', '/tmp/tmpslhgjplp']
[2025-07-09T18:14:55.188+0000] {standard_task_runner.py:91} INFO - Job 35: Subtask download_and_parse_github_data
[2025-07-09T18:14:55.199+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-09T18:14:55.224+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_github_inference.download_and_parse_github_data manual__2025-07-09T18:09:43.991049+00:00 [running]> on host dbf9e19c1827
[2025-07-09T18:14:55.284+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='rajat' AIRFLOW_CTX_DAG_ID='daily_github_inference' AIRFLOW_CTX_TASK_ID='download_and_parse_github_data' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T18:09:43.991049+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-09T18:09:43.991049+00:00'
[2025-07-09T18:14:55.285+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-09T18:14:55.295+0000] {logging_mixin.py:188} INFO - [INFO] Starting ingestion for timestamp: 2025-07-08-15
[2025-07-09T18:14:55.296+0000] {logging_mixin.py:188} INFO - [INFO] Raw file already exists: data/raw/2025-07-08-15.json.gz
[2025-07-09T18:14:59.384+0000] {local_task_job_runner.py:124} ERROR - Received SIGTERM. Terminating subprocesses
[2025-07-09T18:14:59.616+0000] {process_utils.py:132} INFO - Sending 15 to group 567. PIDs of all processes in the group: [567]
[2025-07-09T18:14:59.617+0000] {process_utils.py:87} INFO - Sending the signal 15 to group 567
[2025-07-09T18:14:59.645+0000] {taskinstance.py:2611} ERROR - Received SIGTERM. Terminating subprocesses.
[2025-07-09T18:14:59.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-09T18:14:59.692+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/daily_github_inference.py", line 35, in run_ingestion_wrapper
    run_ingestion(timestamp=ts)
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 81, in run_ingestion
    df = parse_gharchive_json_gz(raw_path, max_events=max_events)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/github_pipeline/parse_gharchive.py", line 57, in parse_gharchive_json_gz
    event = json.loads(line)
            ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 299, in loads
    def loads(s, *, cls=None, object_hook=None, parse_float=None,
    
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2613, in signal_handler
    raise AirflowTaskTerminated("Task received SIGTERM signal")
airflow.exceptions.AirflowTaskTerminated: Task received SIGTERM signal
[2025-07-09T18:14:59.703+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=daily_github_inference, task_id=download_and_parse_github_data, run_id=manual__2025-07-09T18:09:43.991049+00:00, execution_date=20250709T180943, start_date=20250709T181455, end_date=20250709T181459
[2025-07-09T18:14:59.742+0000] {process_utils.py:80} INFO - Process psutil.Process(pid=567, status='terminated', exitcode=2, started='18:14:54') (567) terminated with exit code 2
[2025-07-09T18:14:59.743+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 143
[2025-07-09T18:14:59.791+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-09T18:15:00.106+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
