[2025-07-04T14:45:51.740+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-07-04T14:45:51.920+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-04T14:45:40.602955+00:00 [queued]>
[2025-07-04T14:45:51.973+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-04T14:45:40.602955+00:00 [queued]>
[2025-07-04T14:45:51.976+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-07-04T14:45:52.027+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): run_drift_monitoring> on 2025-07-04 14:45:40.602955+00:00
[2025-07-04T14:45:52.077+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'daily_monitoring_dag', 'run_drift_monitoring', 'manual__2025-07-04T14:45:40.602955+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/monitoring_dag.py', '--cfg-path', '/tmp/tmppv0knepa']
[2025-07-04T14:45:52.092+0000] {standard_task_runner.py:91} INFO - Job 4: Subtask run_drift_monitoring
[2025-07-04T14:45:52.081+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=277) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-07-04T14:45:52.094+0000] {standard_task_runner.py:63} INFO - Started process 293 to run task
[2025-07-04T14:45:52.130+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-07-04T14:45:52.217+0000] {task_command.py:426} INFO - Running <TaskInstance: daily_monitoring_dag.run_drift_monitoring manual__2025-07-04T14:45:40.602955+00:00 [running]> on host e8e8a486d025
[2025-07-04T14:45:52.530+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_monitoring_dag' AIRFLOW_CTX_TASK_ID='run_drift_monitoring' AIRFLOW_CTX_EXECUTION_DATE='2025-07-04T14:45:40.602955+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-07-04T14:45:40.602955+00:00'
[2025-07-04T14:45:52.539+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-07-04T14:45:52.562+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-07-04T14:45:52.563+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/monitoring_dag.py", line 27, in run_monitoring_wrapper
    run_monitoring(reference_ts=reference_ts, current_ts=current_ts)
  File "/opt/airflow/github_pipeline/monitor.py", line 24, in run_monitoring
    raise FileNotFoundError(f"[ERROR] Reference file not found: {ref_file}")
FileNotFoundError: [ERROR] Reference file not found: data/features/actor_features_2025-07-04-15.parquet
[2025-07-04T14:45:52.599+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=daily_monitoring_dag, task_id=run_drift_monitoring, run_id=manual__2025-07-04T14:45:40.602955+00:00, execution_date=20250704T144540, start_date=20250704T144551, end_date=20250704T144552
[2025-07-04T14:45:52.640+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 4 for task run_drift_monitoring ([ERROR] Reference file not found: data/features/actor_features_2025-07-04-15.parquet; 293)
[2025-07-04T14:45:52.723+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-07-04T14:45:52.792+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-07-04T14:45:52.803+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
